listener 1883
persistence true
allow_anonymous false

auth_plugin /mosquitto/go-auth.so

auth_opt_backends http
auth_opt_http_host observatorio_api
auth_opt_http_port 8000

auth_opt_http_getuser_uri /api/mqtt/auth
auth_opt_http_aclcheck_uri /api/mqtt/acl

auth_opt_disable_superuser true
